chore: update bash bin scripts
improve errors handling and simplify structures

chore(ssh): disable port forwarding the phone & set explicit ip
chore(wezterm): update theme to Argonaut

diff --git a/bin/.local/bin/extract b/bin/.local/bin/extract
--- a/bin/.local/bin/extract
+++ b/bin/.local/bin/extract
@@ -1,24 +1,23 @@
 #!/usr/bin/env bash
 set -euo pipefail
 
-PROGNAME="$(basename "$0")"
-
 if [[ $# -eq 0 ]]; then
-  echo "Usage: $PROGNAME <file>"
+  echo "Usage:"
+  echo "    ${0##*/} <file>"
   exit 1
 fi
 
 FILE="$1"
 
 if [[ ! -f "$FILE" ]]; then
-  echo "File '$FILE' does not exist or is not a regular file"
+  echo "File '$FILE' does not exist or is not a regular file" >&2
   exit 1
 fi
 
 case "$FILE" in
   *.tar* | *.tgz | *.tbz2 | *.txz) tar xf "$FILE" ;;
-  *.zip | *.apk) unzip "$FILE" ;;
-  *.7z | *.iso) 7z x "$FILE" ;;
+  *.zip) unzip "$FILE" ;;
+  *.7z) 7z x "$FILE" ;;
   *.rar) unrar x "$FILE" ;;
   *.gz) gunzip "$FILE" ;;
   *.bz2) bunzip2 "$FILE" ;;
@@ -27,6 +26,6 @@ case "$FILE" in
   *.pax.Z) uncompress --stdout "$FILE" | pax -r ;;
   *.Z) uncompress "$FILE" ;;
   *)
-    echo "File '$FILE' cannot be extracted via $PROGNAME"
+    echo "File '$FILE' cannot be extracted via $PROGNAME" >&2
     ;;
 esac
diff --git a/bin/.local/bin/uber-apk-signer b/bin/.local/bin/uber-apk-signer
--- a/bin/.local/bin/uber-apk-signer
+++ b/bin/.local/bin/uber-apk-signer
@@ -4,13 +4,13 @@ set -euo pipefail
 SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
 JAR_FILE="$SCRIPT_DIR/uber-apk-signer.jar"
 
-if ! command -v java >/dev/null 2>&1; then
-  echo "Error: Java is not installed" >&2
+if ! command -v java &>/dev/null; then
+  echo "Java is not installed" >&2
   exit 1
 fi
 
 if [[ ! -f "$JAR_FILE" ]]; then
-  echo "Error: JAR File not found at: $JAR_FILE" >&2
+  echo "JAR File not found at: $JAR_FILE" >&2
   exit 1
 fi
 
