feat(avd): add flags handling
chore: update bash aliases
refactor: update error messages
chore(ssh): update ssh config

diff --git a/bin/.local/bin/extract b/bin/.local/bin/extract
--- a/bin/.local/bin/extract
+++ b/bin/.local/bin/extract
@@ -7,25 +7,26 @@ if [[ $# -eq 0 ]]; then
   exit 1
 fi
 
-FILE="$1"
+file="$1"
 
-if [[ ! -f "$FILE" ]]; then
-  echo "File '$FILE' does not exist or is not a regular file" >&2
+if [[ ! -f "$file" ]]; then
+  echo "'$file' does not exist or is not a regular file" >&2
   exit 1
 fi
 
-case "$FILE" in
-  *.tar* | *.tgz | *.tbz2 | *.txz) tar xf "$FILE" ;;
-  *.zip) unzip "$FILE" ;;
-  *.7z) 7z x "$FILE" ;;
-  *.rar) unrar x "$FILE" ;;
-  *.gz) gunzip "$FILE" ;;
-  *.bz2) bunzip2 "$FILE" ;;
-  *.xz) xz -d "$FILE" ;;
-  *.pax) pax -r <"$FILE" ;;
-  *.pax.Z) uncompress --stdout "$FILE" | pax -r ;;
-  *.Z) uncompress "$FILE" ;;
+case "$file" in
+  *.tar* | *.tgz | *.tbz2 | *.txz) tar xf "$file" ;;
+  *.zip) unzip "$file" ;;
+  *.7z) 7z x "$file" ;;
+  *.rar) unrar x "$file" ;;
+  *.gz) gunzip "$file" ;;
+  *.bz2) bunzip2 "$file" ;;
+  *.xz) xz -d "$file" ;;
+  *.pax) pax -r <"$file" ;;
+  *.pax.Z) uncompress --stdout "$file" | pax -r ;;
+  *.Z) uncompress "$file" ;;
   *)
-    echo "File '$FILE' cannot be extracted via $PROGNAME" >&2
+    echo "Failed to extract '$file'" >&2
+    exit 1
     ;;
 esac
