chore: big refactor & delete unused files/scripts

diff --git a/bin/.local/bin/extract b/bin/.local/bin/extract
--- a/bin/.local/bin/extract
+++ b/bin/.local/bin/extract
@@ -1,31 +1,31 @@
 #!/usr/bin/env bash
 set -euo pipefail
 
-if [[ $# -eq 0 ]]; then
-  echo "Usage:  ${0##*/} <file>"
+if [[ $# -ne 1 ]]; then
+  echo "Usage: ${0##*/} <file>"
   exit 1
 fi
 
-file="$1"
+FILE="$1"
 
-if [[ ! -f "$file" ]]; then
-  echo "'$file' does not exist or is not a regular file" >&2
+if [[ ! -f "$FILE" ]]; then
+  echo "'$FILE' does not exist or is not a regular file" >&2
   exit 1
 fi
 
-case "$file" in
-  *.tar* | *.tgz | *.tbz2 | *.txz) tar xf "$file" ;;
-  *.zip) unzip "$file" ;;
-  *.7z) 7z x "$file" ;;
-  *.rar) unrar x "$file" ;;
-  *.gz) gunzip "$file" ;;
-  *.bz2) bunzip2 "$file" ;;
-  *.xz) xz -d "$file" ;;
-  *.pax) pax -r <"$file" ;;
-  *.pax.Z) uncompress --stdout "$file" | pax -r ;;
-  *.Z) uncompress "$file" ;;
+case "$FILE" in
+  *.tar* | *.tgz | *.tbz2 | *.txz) tar xf "$FILE" ;;
+  *.zip) unzip "$FILE" ;;
+  *.7z) 7z x "$FILE" ;;
+  *.rar) unrar x "$FILE" ;;
+  *.gz) gunzip "$FILE" ;;
+  *.bz2) bunzip2 "$FILE" ;;
+  *.xz) xz -d "$FILE" ;;
+  *.pax) pax -r <"$FILE" ;;
+  *.pax.Z) uncompress --stdout "$FILE" | pax -r ;;
+  *.Z) uncompress "$FILE" ;;
   *)
-    echo "Failed to extract '$file'" >&2
+    echo "Failed to extract '$FILE'" >&2
     exit 1
     ;;
 esac
