feat: add whatip bash helper function
chore: remove whatip bash alias

diff --git a/bash/.local/share/bash-helpers/utils b/bash/.local/share/bash-helpers/utils
--- a/bash/.local/share/bash-helpers/utils
+++ b/bash/.local/share/bash-helpers/utils
@@ -1,5 +1,20 @@
 #!/usr/bin/env bash
 
+whatip() {
+  echo "Public IP:"
+  if ping -c 1 -W 1 1.1.1.1 &>/dev/null; then
+    printf "  %s\n" \
+      "$(curl -s --max-time 2 ifconfig.me || echo 'failed to fetch')"
+  else
+    echo "  (offline)"
+  fi
+
+  echo "Local IP(s):"
+  ip -4 -o addr show scope global |
+    awk '{printf "  %-8s %s\n", $2":", $4}' |
+    cut -d/ -f1
+}
+
 gpg-here() {
   local dirpath="$PWD/.gnupg"
   export GNUPGHOME="$dirpath"
